version: "3"
services:
  frontend:
    build: ./
    command: sh -c "yarn run dev"
    container_name: "Portfolio_Frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    stdin_open: true
    tty: true
